# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np
import random

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1d = np.array([1,2,3,4,5])

# Create a 2-dimensional NumPy array using np.array()
a2d = np.array([[1,2,3,4], [5,6,7,8]])

# Create a 3-dimensional Numpy array using np.array()
a3d = np.array([[[1, 2, 3], [4,5,6]], [[7,8,9], [10,11,12]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
print(a1d.shape)
print(a1d.ndim)
print(a1d.dtype)
print(a1d.size)
print(type(a1d))

(5,)
1
int64
5
<class 'numpy.ndarray'>


In [4]:
# Attributes of 2-dimensional array
print(a2d.shape)
print(a2d.ndim)
print(a2d.dtype)
print(a2d.size)
print(type(a2d))

(2, 4)
2
int64
8
<class 'numpy.ndarray'>


In [5]:
# Attributes of 3-dimensional array
print(a3d.shape)
print(a3d.ndim)
print(a3d.dtype)
print(a3d.size)
print(type(a3d))

(2, 2, 3)
3
int64
12
<class 'numpy.ndarray'>


In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a1d, index = list("abcde"), columns = list("A"))
df2 = pd.DataFrame(a2d, index = list("ab"), columns = list("ABCD"))

print(df)
print(df2)


   A
a  1
b  2
c  3
d  4
e  5
   A  B  C  D
a  1  2  3  4
b  5  6  7  8


In [7]:
# Create an array of shape (10, 2) with only ones
arr1s = np.ones((10,2))
print(arr1s)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
# Create an array of shape (7, 2, 3) of only zeros
arr0 = np.zeros((7, 2, 3))
print(arr0)


[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [9]:
# Create an array within a range of 0 and 100 with step 3
arr_range = np.arange(0, 100, 3)
print(arr_range)


[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr_r1 = np.random.randint(10, size = (7, 2))
print(arr_r1)

[[8 4]
 [6 1]
 [1 8]
 [2 7]
 [7 9]
 [9 7]
 [3 9]]


In [14]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
from numpy import random
arr_r2 = random.rand(3,5)
print(arr_r2)



[[0.83551414 0.75546382 0.68120248 0.9276463  0.33854951]
 [0.94498753 0.84325457 0.87582293 0.80555099 0.60029531]
 [0.50394418 0.03984106 0.84763912 0.663664   0.81097453]]


In [15]:
# Set the random seed to 42
random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr3 = np.random.randint(10, size = (4, 6))
print(arr3)


[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [16]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr4 = np.random.randint(1, 10, size = (3, 7))
print(arr4)


# Find the unique numbers in the array you just created


[[9 1 3 7 4 9 3]
 [5 3 7 5 9 7 2]
 [4 9 2 9 5 2 4]]


In [18]:
# Find the 0'th index of the latest array you created
print(arr4[0])


[9 1 3 7 4 9 3]


In [19]:
# Get the first 2 rows of latest array you created
print(arr4[0])
print(arr4[1])

[9 1 3 7 4 9 3]
[5 3 7 5 9 7 2]


In [20]:
# Get the first 2 values of the first 2 rows of the latest array
print(arr4[0, 0], arr4[0, 1])
print(arr4[1, 0], arr4[1, 1])

9 1
5 3


In [21]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr5 = np.random.randint(10, size = (3, 5))
arr6 = np.ones((3, 5), dtype = 'i')
print(arr5)
print(arr6)



[[6 7 2 0 3]
 [1 7 3 1 5]
 [5 9 3 5 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [22]:
# Add the two arrays together
added = np.concatenate((arr5, arr6))
print(added)

[[6 7 2 0 3]
 [1 7 3 1 5]
 [5 9 3 5 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [23]:
# Create another array of ones of shape (5, 3)
arr7 = np.ones((5, 3), dtype = 'i')
print(arr7)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# Try add the array of ones and the other most recent array together
# added2 = np.concatenate((arr7, arr5))


When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [24]:
# Create another array of ones of shape (3, 5)
arr8 = np.ones((3, 5), dtype='i')
print(arr8)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [26]:
# Subtract the new array of ones from the other most recent array
sub = arr5 - arr8
print(sub)

[[ 5  6  1 -1  2]
 [ 0  6  2  0  4]
 [ 4  8  2  4  0]]


In [27]:
# Multiply the ones array with the latest array
mul = arr8 * sub
print(mul)

[[ 5  6  1 -1  2]
 [ 0  6  2  0  4]
 [ 4  8  2  4  0]]


In [28]:
# Take the latest array to the power of 2 using '**'
pwr2 = mul ** 2
print(pwr2)


[[25 36  1  1  4]
 [ 0 36  4  0 16]
 [16 64  4 16  0]]


In [29]:
# Do the same thing with np.square()
sqr = np.square(mul)
print(sqr)

[[25 36  1  1  4]
 [ 0 36  4  0 16]
 [16 64  4 16  0]]


In [30]:
# Find the mean of the latest array using np.mean()
mean = np.mean(sqr)
print(mean)

14.866666666666667


In [31]:
# Find the maximum of the latest array using np.max()
max = np.max(sqr)
print(max)

64


In [32]:
# Find the minimum of the latest array using np.min()
min = np.min(sqr)
print(min)

0


In [33]:
# Find the standard deviation of the latest array
sd = np.std(sqr)
print(sd)

17.917837171067518


In [34]:
# Find the variance of the latest array
var = np.var(sqr)
print(var)

321.0488888888889


In [35]:
# Reshape the latest array to (3, 5, 1)
sqr.reshape(3, 5, 1)
print(sqr)

[[25 36  1  1  4]
 [ 0 36  4  0 16]
 [16 64  4 16  0]]


In [36]:
# Transpose the latest array
trans = np.transpose(sqr)
print(trans)

[[25  0 16]
 [36 36 64]
 [ 1  4  4]
 [ 1  0 16]
 [ 4 16  0]]


What does the transpose do?

In [ ]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr10 = np.random.randint(10, size = (3, 3))
arr11 = np.random.randint(10, size = (3, 2))
print(arr10)
print(arr11)

In [ ]:
# Perform a dot product on the two newest arrays you created
x = np.dot(arr10, arr11)
print(x)

In [ ]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr12 = np.random.randint(10, size = (4, 3))
arr13 = np.random.randint(10, size = (4, 3))
print(arr12)
print(arr13)

In [ ]:
# Perform a dot product on the two newest arrays you created
# x = np.dot(arr12, arr13)


It doesn't work. How would you fix it?

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
arr13 = np.transpose(arr13)
x = np.dot(arr12, arr13)
print(x)


In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr14 = np.random.randint(10, size = (3, 5))
arr15 = np.random.randint(10, size = (3, 5))
print(arr14)
print(arr15)

In [ ]:
# Compare the two arrays with '>'
flag = arr14 > arr15
print(flag)

What happens when you compare the arrays with `>`?

In [ ]:
# Compare the two arrays with '>='
print(arr14 >= arr15)


In [ ]:
# Find which elements of the first array are greater than 7
for x in np.nditer(arr14):
  if(x > 7):
    print(x)

In [ ]:
# Which parts of each array are equal? (try using '==')
print(arr14 == arr15)

In [ ]:
# Sort one of the arrays you just created in ascending order
arr15.sort()
print(arr15)

In [ ]:
# Sort the indexes of one of the arrays you just created
arr16 = np.argsort(arr15)
print(arr16)

In [ ]:
# Find the index with the maximum value in one of the arrays you've created
x = np.argmax(arr15)
print(x)

In [ ]:
# Find the index with the minimum value in one of the arrays you've created
y = np.argmin(arr15)
print(y)

In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
z = np.argmax(arr15, axis = 1)
print(z)

In [ ]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
w = np.argmin(arr15, axis = 0)
print(w)

In [ ]:
# Create an array of normally distributed random numbers
arr17 = np.random.normal(size = 10)
print(arr17)


In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100
arr18 = np.linspace(1, 100, num=10, dtype='i')
print(arr18)

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.